# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
        
    - name: Install mesmerize-core
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt
        pip install pytest
        pip install .
        
    - name: install caiman
      run: |
        git clone https://github.com/kushalkolar/CaImAn.git
        cd CaImAn
        git checkout mcorr-basename-prefix
        pip install -r requirements.txt
        pip install .
        
    - name: Test with pytest
      run: |
        pytest .
